### ISSUE TITLE
Scaling constant

### ISSUE THREAD

**Issue by bicycle1885** [MurrellGroup/InvariantPointAttention.jl#6]
I believe this has very little (or no) effects in practice but if you care about the rationale behind this constant factor you should change it to $1/\sqrt{2}$ iff `zij` is `nothing`.
https://github.com/MurrellGroup/InvariantPointAttention.jl/blob/d77893122ebb02c07704637dfbc371ea3793fdf3/src/layers.jl#L130

The reason why the denominator of this constant is three is because we add three terms when calculating attention scores. So, if you omit the bias term (`zij`), the reasonable choice is changing it to two because we add only two terms there.

**Comment by billera** [comment]
Thank you for the insight!
